### ISSUE TITLE
Issue with contexthub.assetsharecommonscart and  cart.store is not a function

### ISSUE THREAD

**Issue by venkat603** [adobe/asset-share-commons#703]
Hi Team,

I am trying to use cart store on AEM 6.5.10 which is from asset-share-commons.  We recently upgraded to 6.5.10 from 6.3.  

In 6.3 we used 1.6.10 asset share commons  after upgrading to 6.5.10 we used 2.0.6 asset-share-commons.

We have changed all the paths related to contexthub and cleintlibs to Conf folder.  

We are using AssestShare Cart for one of the components while loading the store which used in 1.6.10 "contexthub.assetsharecommonscart" in clientlib-contexthub\cart\store.assetsharecommonscart.js , we are facing below issue as attached.  I see there is no where they are calling  "contexthub.assetsharecommonscart in 2.0.6.  Can you look into this.

![image](https://user-images.githubusercontent.com/101249140/157433229-94d1bc09-3b28-44e0-a2c9-81b204d7fda3.png)
