### PR TITLE
Also load DS components and Sling Models from fragment bundles

### LINKED ISSUE #828: Download is not working with 2.4 version
I have installed the latest 2.4 version on AEM with sample content but downloading the asset shows this on browser:

The web page at *http://localhost:6502/content/asset-share-commons/en/light/actions/download/_jcr_content/root/responsivegrid/download.download-asset-renditions.zip* might be temporarily down or it may have moved permanently to a new web address

in the error.log:

```
POST /content/asset-share-commons/en/light/actions/download/_jcr_content/root/responsivegrid/download.download-asset-renditions.zip HTTP/1.1] org.apache.sling.engine.impl.SlingRequestProcessorImpl service: Uncaught Throwable
java.lang.NoClassDefFoundError: com/adobe/acs/commons/util/BufferedServletOutput
```

Moreover, the Downloads component on downloads page(/content/asset-share-commons/en/light/actions/downloads) also giving the below error while adding:

```
GET asset-share-commons/en/light/actions/downloads/jcr:content/root/downloads.html HTTP/1.1] org.apache.sling.engine.impl.SlingRequestProcessorImpl service: Uncaught Throwable
org.apache.sling.scripting.sightly.SightlyException: Compilation errors in org/apache/sling/scripting/sightly/apps/asset__002d__share__002d__commons/components/modals/downloads/downloads__002e__html.java:_Line 53, column 2649 : com.adobe.aem.commons.assetshare.components.actions.downloads.Downloads cannot be resolved to a type
```
this class Downloads.java exist in the 2.3 version but not anymore on 2.4:
```
2.3.4: https://github.com/adobe/asset-share-commons/tree/asset-share-commons-2.3.4/core/src/main/java/com/adobe/aem/commons/assetshare/components/actions
```

```
2.4:https://github.com/adobe/asset-share-commons/tree/asset-share-commons-2.4.0/core/src/main/java/com/adobe/aem/commons/assetshare/components/actions
```

but the component /apps/asset-share-commons/components/modals/downloads/downloads.html still referring the class com.adobe.aem.commons.assetshare.components.actions.downloads.Downloads

this is re-producible on both AEM6.5 and AEM SDK

### PR DESCRIPTION
**Pull request by kwin**
This closes #828

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: core/pom.xml [hunk 1]
```diff
@@ -39,6 +39,15 @@
 Bundle-Name: Asset Share Commons - Core
 Bundle-Description: Asset Share Commons Core OSGi bundle containing AEM server-side logic
 Bundle-SymbolicName: com.adobe.aem.commons.assetshare.core
+# also detect scr descriptors from bundle fragments (https://docs.osgi.org/specification/osgi.cmpn/8.0.0/service.component.html#d0e30931)
+Service-Component: OSGI-INF/*.xml
+# reference packages from both fragment and this bundle: https://sling.apache.org/documentation/bundles/models.html#bundle-manifest-configuration
+Sling-Model-Packages: com.adobe.aem.commons.assetshare.components,\
```
Comment (kwin) [inline core/pom.xml:45]: this can be simplified to just `com.adobe.aem.commons.assetshare` with the drawback of slightly decreased speed of https://github.com/apache/sling-org-apache-sling-models-impl/blob/6c3baab6bb71c329170fdeb0250db4c78a5cdb1d/src/main/java/org/apache/sling/models/impl/ModelPackageBundleListener.java#L114

**Review by davidjgonzalez — APPROVED** [review]
