### ISSUE TITLE
Download is not working with 2.4 version

### ISSUE THREAD

**Issue by vivekmalviya0104** [adobe/asset-share-commons#828]
I have installed the latest 2.4 version on AEM with sample content but downloading the asset shows this on browser:

The web page at *http://localhost:6502/content/asset-share-commons/en/light/actions/download/_jcr_content/root/responsivegrid/download.download-asset-renditions.zip* might be temporarily down or it may have moved permanently to a new web address

in the error.log:

```
POST /content/asset-share-commons/en/light/actions/download/_jcr_content/root/responsivegrid/download.download-asset-renditions.zip HTTP/1.1] org.apache.sling.engine.impl.SlingRequestProcessorImpl service: Uncaught Throwable
java.lang.NoClassDefFoundError: com/adobe/acs/commons/util/BufferedServletOutput
```

Moreover, the Downloads component on downloads page(/content/asset-share-commons/en/light/actions/downloads) also giving the below error while adding:

```
GET asset-share-commons/en/light/actions/downloads/jcr:content/root/downloads.html HTTP/1.1] org.apache.sling.engine.impl.SlingRequestProcessorImpl service: Uncaught Throwable
org.apache.sling.scripting.sightly.SightlyException: Compilation errors in org/apache/sling/scripting/sightly/apps/asset__002d__share__002d__commons/components/modals/downloads/downloads__002e__html.java:_Line 53, column 2649 : com.adobe.aem.commons.assetshare.components.actions.downloads.Downloads cannot be resolved to a type
```
this class Downloads.java exist in the 2.3 version but not anymore on 2.4:
```
2.3.4: https://github.com/adobe/asset-share-commons/tree/asset-share-commons-2.3.4/core/src/main/java/com/adobe/aem/commons/assetshare/components/actions
```

```
2.4:https://github.com/adobe/asset-share-commons/tree/asset-share-commons-2.4.0/core/src/main/java/com/adobe/aem/commons/assetshare/components/actions
```

but the component /apps/asset-share-commons/components/modals/downloads/downloads.html still referring the class com.adobe.aem.commons.assetshare.components.actions.downloads.Downloads

this is re-producible on both AEM6.5 and AEM SDK

**Comment by davidjgonzalez** [comment]
Are you using the cloud classifier in your ASC all maven dependency?

https://opensource.adobe.com/asset-share-commons/pages/getting-started/new-project/

   <dependency>
    <groupId>com.adobe.aem.commons</groupId>
    <artifactId>assetshare.all</artifactId>
    <version>2.x.x</version>
    <classifier>cloud</classifier>
    <type>zip</type>
  </dependency>

**Comment by vivekmalviya0104** [comment]
Hello David,
Thanks for your response. Indeed the dependencies are there and I can see both core and core-fragment bundle Active in the console:
![Screenshot 2022-10-25 at 15 07 37](https://user-images.githubusercontent.com/80326802/197781237-2e32a8af-bcf2-466f-a10e-1723ab98c436.png)

**Comment by davidjgonzalez** [comment]
@kwin it doesnt appear that Sling Models or OSGi components are being registered from the new Core Cloud Fragment bundle. Any idea what could be going on? 

For example, The RequireAemCanaryImpl is not being recognized as a OSGi component/service for RequireAemCanary - thus making ASC think its running on AEM Classic and not AEM CS.

Similarly, it doesnt appear the Downloads Sling Model (in the Fragment build) is being registered a a Sling Model.

**Comment by kwin** [comment]
For Sling Models the bundle manifest configuration for models (https://sling.apache.org/documentation/bundles/models.html#bundle-manifest-configuration) from the fragment is not considered due to https://docs.osgi.org/specification/osgi.core/7.0.0/framework.module.html#framework.module.fragmentbundles (i.e. only very few manifest headers are merged).

**Comment by vivekmalviya0104** [comment]
Hello @davidjgonzalez , @kwin , 
Thanks a lot for fixing it. Could you please tell me how I can integrate this fix within the release 2.4.0 which I am already using in my current project ?

**Comment by davidjgonzalez** [comment]
Thanks for @kwin for the quick fix!

@vivekmalviya0104  the fix is in ASC v2.4.2 - can you upgrade to that please?

**Comment by vivekmalviya0104** [comment]
@davidjgonzalez , yes after upgrading to 2.4.2 it works!
thanks a lot again.
